spring:  
  application:
    name: clients-service
  cloud:
    # Ribbon
    loadbalancer:
      ribbon:
        enabled: false
---
spring:
  profiles: dev
  cloud:
    # Kubernetes
    kubernetes:
      enabled: false
    # Consul
    consul:
      enabled: true
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-url: http://${spring.cloud.client.hostname}:8080/actuator/health