version: '3.7'

services:

    auth-service:
        build:
            context: auth-service
            dockerfile: dev.dockerfile
        restart: unless-stopped
        ports:
            - "8080:8080"

networks:
    backend: 